### ISSUE TITLE
Importing files without default export

### ISSUE THREAD

**Issue by martinchrzan-workday** [digital-loukoum/tsc-esm#9]
I have ts file with following imports (I just need to import and run that .ts script, it has no exports)

file.ts

```
import '../setup1'
import '../setup2'
```

It results in
file.js

```
import undefined from '../setup1.js';
import undefined from '../setup2.js';
```

which is obviously wrong and running this will fail as we are having import with the same name, it should result into this

file.js
```
import '../setup1.js'
import '../setup2.js'
```

**Comment by joekukish** [comment]
I'm having the same issue. In my case these are files that are imported for the side effects (web-components). @Gin-Quin any chance you could have a look?

**Comment by Gin-Quin** [comment]
I strongly recommend to not use tsc-eam and instead to follow recent Typescript guidelines (starting from Typescript 4.7) to add the extension name (".js") at the end of the import.

This is future-proof (unlike tsc-esm). 

Anyway I will look at this bug when I have some time.

**Comment by joekukish** [comment]
@Gin-Quin I've made a PR for this: https://github.com/digital-loukoum/grubber/pull/4

The problem is that even with TS 4.7.4, webpack complains about the extensions so at the time being something like `tsc-esm` is the best choice.

**Comment by martinchrzan-workday** [comment]
@Gin-Quin that guideline is still wrong in my and many others opinion - you are suppose to import file which does not exist in your file system before transpilation

**Comment by martinchrzan-workday** [comment]
@joekukish I am currently solving it with a simple script which I run after tsc-esm:

```
import replace from 'replace-in-file';

const importsFix = {
  files: ['dist/**/*.js'],
  from: /import undefined from/g,
  to: 'import',
};
```

**Comment by Gin-Quin** [comment]
> @Gin-Quin that guideline is still wrong in my and many others opinion - you are suppose to import file which does not exist in your file system before transpilation 

I agree with you, importing a yet non-existant ".js" file feels wrong. It would have made more sense to add the ".ts" extension and then the compiler would transform into ".js".

But the typescript team is extremely reluctant to perform transformations. They want to stick to the Javascript language as much as possible. I think it's a mistake because they already do transformations: whenever you define an enum for example.

I know there is this proposal to make Typescript types accepted (ignored) by the browser (and by extension, Node). That would be huge because you would only write Javascript files, no more Typescript files. It would be a complete merge of the two languages. 
If this happens (and I guess it's their long-term plan) then it makes sense to write the ".js" extension.

But before we get to this point, I've got used to add this weird ".js" extension. My imports are automatically done 90% of the time so I'm not even writing them myself. Also it feels safer not telling the compiler "guess which file I'm talking about", the extension removes an ambiguity. Especially in a front-end world where you can also import css, jpeg, html, etc... 

I'm in holidays so I can't resolve this for now, but I'll do it when I'm back.

**Comment by joekukish** [comment]
@Gin-Quin the problem is that the whole ecosystem is still fragmented regarding this. I've tried adding `.js` to every import to please browsers (so I can run tachometer comparisons against main), and then webpack complains about the extensions.

**Comment by Gin-Quin** [comment]
Oh, I didn't know about Webpack (I'm a Vite guy). It should work since `tsc-esm@3.1.4` 👍
